apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: podinfo
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: releases/devcluster/release/podinfo
    repoURL: https://github.com/thomasjackson-clari/k8s.git
    targetRevision: HEAD
