apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- example/Deployment-release-name-hello-world.yaml
- example/Namespace-example.yaml
- example/RoleBinding-k8s-users.yaml
- example/Service-release-name-hello-world.yaml
- example/ServiceAccount-release-name-hello-world.yaml
- examplechange/Deployment-release-name-hello-world.yaml
- examplechange/Namespace-examplechange.yaml
- examplechange/RoleBinding-k8s-users.yaml
- examplechange/Service-release-name-hello-world.yaml
- examplechange/ServiceAccount-release-name-hello-world.yaml
- podinfo-helm/Deployment-release-name-podinfo.yaml
- podinfo-helm/Namespace-podinfo-helm.yaml
- podinfo-helm/RoleBinding-k8s-users.yaml
- podinfo-helm/Service-release-name-podinfo.yaml
- podinfo/Deployment-podinfo.yaml
- podinfo/HorizontalPodAutoscaler-podinfo.yaml
- podinfo/Namespace-podinfo.yaml
- podinfo/RoleBinding-k8s-users.yaml
- podinfo/Service-podinfo.yaml
