approval_rules:
- if:
    changed_files:
      paths:
      - ^releases/prodcluster/example.*$
  name: owner_regular-prodcluster/example
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users: &id001
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/prodcluster/example.*$
  name: owner_override-prodcluster/example
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users: *id001
- if:
    changed_files:
      paths:
      - ^releases/prodcluster/podinfo.*$
  name: owner_regular-prodcluster/podinfo
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users: &id002
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/prodcluster/podinfo.*$
  name: owner_override-prodcluster/podinfo
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users: *id002
- if:
    changed_files:
      paths:
      - ^releases/devcluster/example.*$
  name: owner_regular-devcluster/example
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users: &id003
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/devcluster/example.*$
  name: owner_override-devcluster/example
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users: *id003
- if:
    changed_files:
      paths:
      - ^releases/devcluster/podinfo.*$
  name: owner_regular-devcluster/podinfo
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users: &id004
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/devcluster/podinfo.*$
  name: owner_override-devcluster/podinfo
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users: *id004
- if:
    changed_files:
      paths:
      - ^releases/stagecluster/example.*$
  name: owner_regular-stagecluster/example
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users: &id005
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/stagecluster/example.*$
  name: owner_override-stagecluster/example
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users: *id005
- if:
    changed_files:
      paths:
      - ^releases/stagecluster/podinfo.*$
  name: owner_regular-stagecluster/podinfo
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users: &id006
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/stagecluster/podinfo.*$
  name: owner_override-stagecluster/podinfo
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users: *id006
- if:
    changed_files:
      paths:
      - ^.*$
  name: admin_override
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
policy:
  approval:
  - or:
    - and:
      - owner_regular-prodcluster/example
      - owner_regular-prodcluster/podinfo
      - owner_regular-devcluster/example
      - owner_regular-devcluster/podinfo
      - owner_regular-stagecluster/example
      - owner_regular-stagecluster/podinfo
    - and:
      - owner_override-prodcluster/example
      - owner_override-prodcluster/podinfo
      - owner_override-devcluster/example
      - owner_override-devcluster/podinfo
      - owner_override-stagecluster/example
      - owner_override-stagecluster/podinfo
    - admin_override

