approval_rules:
- if:
    changed_files:
      paths: &id001
      - releases/devcluster/release/examplechange/_namespace.yaml
      - releases/devcluster/release/example/_namespace.yaml
      - releases/devcluster/release/podinfo/_namespace.yaml
      - releases/devcluster/release/podinfo-helm/_namespace.yaml
      - releases/stagecluster/release/examplechange/_namespace.yaml
      - releases/stagecluster/release/example/_namespace.yaml
      - releases/stagecluster/release/podinfo/_namespace.yaml
      - releases/stagecluster/release/podinfo-helm/_namespace.yaml
      - releases/prodcluster/release/examplechange/_namespace.yaml
      - releases/prodcluster/release/example/_namespace.yaml
      - releases/prodcluster/release/podinfo/_namespace.yaml
      - releases/prodcluster/release/podinfo-helm/_namespace.yaml
  name: owner_regular-jacksontj
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users: &id002
    - jacksontj
- if:
    changed_files:
      paths: *id001
  name: owner_override-jacksontj
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users: *id002
- if:
    changed_files:
      paths:
      - ^.*$
  name: admin_override
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
policy:
  approval:
  - or:
    - and:
      - owner_regular-jacksontj
    - and:
      - owner_override-jacksontj
    - admin_override

