approval_rules:
- if:
    changed_files:
      paths:
      - ^releases/devcluster/example/.*$
  name: owner_regular-devcluster/example
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/prodcluster/example/.*$
  name: owner_regular-prodcluster/example
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/stagecluster/example/.*$
  name: owner_regular-stagecluster/example
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/devcluster/global/.*$
  name: owner_regular-devcluster/global
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/prodcluster/global/.*$
  name: owner_regular-prodcluster/global
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/stagecluster/global/.*$
  name: owner_regular-stagecluster/global
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/devcluster/kube-state-metrics/.*$
  name: owner_regular-devcluster/kube-state-metrics
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/prodcluster/kube-state-metrics/.*$
  name: owner_regular-prodcluster/kube-state-metrics
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/stagecluster/kube-state-metrics/.*$
  name: owner_regular-stagecluster/kube-state-metrics
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/devcluster/metrics-server/.*$
  name: owner_regular-devcluster/metrics-server
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/prodcluster/metrics-server/.*$
  name: owner_regular-prodcluster/metrics-server
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/stagecluster/metrics-server/.*$
  name: owner_regular-stagecluster/metrics-server
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/devcluster/podinfo/.*$
  name: owner_regular-devcluster/podinfo
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/prodcluster/podinfo/.*$
  name: owner_regular-prodcluster/podinfo
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/stagecluster/podinfo/.*$
  name: owner_regular-stagecluster/podinfo
  options:
    allow_author: false
    invalidate_on_push: true
    methods:
      github_review: true
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/devcluster/example/.*$
  name: owner_override-devcluster/example
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/prodcluster/example/.*$
  name: owner_override-prodcluster/example
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/stagecluster/example/.*$
  name: owner_override-stagecluster/example
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/devcluster/global/.*$
  name: owner_override-devcluster/global
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/prodcluster/global/.*$
  name: owner_override-prodcluster/global
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/stagecluster/global/.*$
  name: owner_override-stagecluster/global
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/devcluster/kube-state-metrics/.*$
  name: owner_override-devcluster/kube-state-metrics
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/prodcluster/kube-state-metrics/.*$
  name: owner_override-prodcluster/kube-state-metrics
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/stagecluster/kube-state-metrics/.*$
  name: owner_override-stagecluster/kube-state-metrics
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/devcluster/metrics-server/.*$
  name: owner_override-devcluster/metrics-server
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/prodcluster/metrics-server/.*$
  name: owner_override-prodcluster/metrics-server
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/stagecluster/metrics-server/.*$
  name: owner_override-stagecluster/metrics-server
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/devcluster/podinfo/.*$
  name: owner_override-devcluster/podinfo
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/prodcluster/podinfo/.*$
  name: owner_override-prodcluster/podinfo
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^releases/stagecluster/podinfo/.*$
  name: owner_override-stagecluster/podinfo
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
- if:
    changed_files:
      paths:
      - ^.*$
  name: admin_override
  options:
    allow_author: true
    invalidate_on_push: true
    methods:
      comments:
      - FORCE_COMMIT
  requires:
    count: 1
    users:
    - jacksontj
policy:
  approval:
  - or:
    - and:
      - owner_regular-devcluster/example
      - owner_regular-prodcluster/example
      - owner_regular-stagecluster/example
      - owner_regular-devcluster/global
      - owner_regular-prodcluster/global
      - owner_regular-stagecluster/global
      - owner_regular-devcluster/kube-state-metrics
      - owner_regular-prodcluster/kube-state-metrics
      - owner_regular-stagecluster/kube-state-metrics
      - owner_regular-devcluster/metrics-server
      - owner_regular-prodcluster/metrics-server
      - owner_regular-stagecluster/metrics-server
      - owner_regular-devcluster/podinfo
      - owner_regular-prodcluster/podinfo
      - owner_regular-stagecluster/podinfo
    - and:
      - owner_override-devcluster/example
      - owner_override-prodcluster/example
      - owner_override-stagecluster/example
      - owner_override-devcluster/global
      - owner_override-prodcluster/global
      - owner_override-stagecluster/global
      - owner_override-devcluster/kube-state-metrics
      - owner_override-prodcluster/kube-state-metrics
      - owner_override-stagecluster/kube-state-metrics
      - owner_override-devcluster/metrics-server
      - owner_override-prodcluster/metrics-server
      - owner_override-stagecluster/metrics-server
      - owner_override-devcluster/podinfo
      - owner_override-prodcluster/podinfo
      - owner_override-stagecluster/podinfo
    - admin_override

