apiVersion: v1
kind: Pod
metadata:
  annotations:
    appmesh.k8s.aws/sidecarInjectorWebhook: disabled
    helm.sh/hook: test-success
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    linkerd.io/inject: disabled
    sidecar.istio.io/inject: "false"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/version: 6.3.5
    helm.sh/chart: podinfo-6.3.5
  name: podinfo-jwt-test-2ci0m
  namespace: podinfo
spec:
  containers:
  - command:
    - sh
    - -c
    - |
      TOKEN=$(curl -sd 'test' ${PODINFO_SVC}/token | jq -r .token) &&
      curl -sH "Authorization: Bearer ${TOKEN}" ${PODINFO_SVC}/token/validate | grep test
    env:
    - name: PODINFO_SVC
      value: podinfo.podinfo:9898
    image: giantswarm/tiny-tools
    name: tools
  restartPolicy: Never
