apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: metrics-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/version: 0.6.4
    helm.sh/chart: metrics-server-3.11.0
  name: metrics-server
  namespace: metrics-server
