apiVersion: v1
kind: Pod
metadata:
  annotations:
    appmesh.k8s.aws/sidecarInjectorWebhook: disabled
    helm.sh/hook: test-success
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    linkerd.io/inject: disabled
    sidecar.istio.io/inject: "false"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/version: 6.3.5
    helm.sh/chart: podinfo-6.3.5
  name: podinfo-grpc-test-8lhox
  namespace: podinfo
spec:
  containers:
  - args:
    - -addr=podinfo.podinfo:9999
    command:
    - grpc_health_probe
    image: stefanprodan/grpc_health_probe:v0.3.0
    name: grpc-health-probe
  restartPolicy: Never
